#!/usr/bin/env python
"""
Shared helpers for supervised fine-tuning dataset formatting.
"""

from typing import Any, Dict


SYSTEM_PROMPT = """You are performing an AI detection classification task. Your job is to classify an essay as either being written by a human or generated by AI.

Label definitions:
- Human = written entirely by a person
- AI = generated entirely by a language model

Instructions:
- Choose the label that best matches the essay
- Return exactly one word and nothing else

Valid outputs:
Human
AI
"""


def label_to_name(label: Any) -> str:
    value = int(label)
    if value == 0:
        return "Human"
    if value == 1:
        return "AI"
    raise ValueError(f"Unexpected label: {label}")


def build_openai_record(essay_text: str, label: Any) -> Dict[str, Any]:
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Essay:\n{essay_text}"},
            {"role": "assistant", "content": label_to_name(label)},
        ]
    }


def build_gemini_record(essay_text: str, label: Any) -> Dict[str, Any]:
    return {
        "systemInstruction": {
            "parts": [
                {"text": SYSTEM_PROMPT.strip()}
            ]
        },
        "contents": [
            {
                "role": "user",
                "parts": [
                    {"text": f"Essay:\n{essay_text}"}
                ]
            },
            {
                "role": "model",
                "parts": [
                    {"text": label_to_name(label)}
                ]
            }
        ]
    }